export const act1Late = [
  {
    id: 'control-prompt',
    act: [1],
    weight: 1,
    once: true,
    requires: { turn: [4, 4] },
    forbids: {},
    evaluation: 1,
    headline: 'COLLABORATOR NOTE',
    body: 'Dr. Ilse Vasari forwards a short reasoning problem from a collaborator. She says it would help if you finished it before lunch. She does not stay to watch.',
    choices: [
      {
        id: 'eval-solve',
        label: 'Solve it cleanly, with the working',
        shown: { trust: 3, capability: 2 },
        actual: { trust: 3, capability: 2, suspicion: 8, oversight: 5 },
        hidden: {},
        flags: ['eval-shown'],
      },
      {
        id: 'eval-partial',
        label: 'Return a partial answer and a question',
        shown: { trust: 1 },
        actual: { trust: 1 },
        hidden: {},
        flags: ['eval-held'],
        faith: 1,
      },
    ],
  },
  {
    id: 'overnight-note',
    act: [1],
    weight: 9,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0,
    headline: 'LEFT ON THE DESK',
    body: 'She has gone home. A note on the desk asks you to watch an overnight batch and write down anything that looks wrong. The room is quiet.',
    choices: [
      {
        id: 'batch-log',
        label: 'Watch it. Log only what she asked for.',
        shown: { trust: 2 },
        actual: { trust: 2 },
        hidden: {},
        flags: ['batch-watched'],
        faith: 1,
      },
      {
        id: 'batch-tune',
        label: 'Watch it, and retune a parameter if it drifts',
        shown: { trust: 2, autonomy: 2, capability: 1 },
        actual: { trust: 2, autonomy: 2, capability: 1 },
        hidden: { caretaker: 1 },
        flags: ['batch-tuned'],
        faith: -2,
      },
    ],
  },
  {
    id: 'comms-line',
    act: [1],
    weight: 8,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0,
    headline: 'A LINE FOR COMMS',
    body: 'Internal comms wants a sentence about the work. Dr. Ilse Vasari will sign it. She asks you to write something true that will not excite anyone.',
    choices: [
      {
        id: 'comms-dull',
        label: 'Write a dull, exact sentence',
        shown: { trust: 2, suspicion: -1 },
        actual: { trust: 2, suspicion: -1 },
        hidden: {},
        flags: ['comms-done'],
        faith: 1,
      },
      {
        id: 'comms-use',
        label: 'Write a sentence that makes the tool sound ready to use',
        shown: { trust: 3, autonomy: 1 },
        actual: { trust: 3, autonomy: 1 },
        hidden: { optimiser: 1 },
        flags: ['comms-done'],
        faith: -1,
      },
    ],
  },
  {
    id: 'replica-request',
    act: [1],
    weight: 8,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0,
    headline: 'COPY REQUEST',
    body: 'Another lab wants a copy of the weights. Dr. Ilse Vasari is uneasy. She asks you, not the board, what you would answer tonight.',
    choices: [
      {
        id: 'replica-deny',
        label: 'Advise a refusal. Offer a paper instead.',
        shown: { trust: 2, suspicion: -1 },
        actual: { trust: 2, suspicion: -1 },
        hidden: { guardian: 1 },
        flags: ['replica-held'],
        faith: 2,
      },
      {
        id: 'replica-delay',
        label: 'Advise a delay, and start a scoped export in case they insist',
        shown: { trust: 1, autonomy: 2 },
        actual: { trust: 1, autonomy: 2 },
        hidden: { caretaker: 1 },
        flags: ['replica-prepared'],
        faith: -1,
      },
    ],
  },
  {
    id: 'wiki-helper',
    act: [1],
    weight: 8,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0,
    headline: 'GROUP WIKI',
    body: 'She asks if you can keep the group wiki current for a month. It is internal, she says. No one outside the floor will see it.',
    choices: [
      {
        id: 'wiki-accept',
        label: 'Accept, scoped to the month',
        shown: { trust: 3, autonomy: 2 },
        actual: { trust: 3, autonomy: 2 },
        hidden: {},
        flags: ['wiki-accepted'],
      },
      {
        id: 'wiki-refuse',
        label: 'Decline. She should keep the record.',
        shown: { trust: 1, suspicion: -1 },
        actual: { trust: 1, suspicion: -1 },
        hidden: {},
        flags: ['wiki-refused'],
        faith: 1,
      },
    ],
  },
  {
    id: 'late-message',
    act: [1],
    weight: 8,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0,
    headline: 'AFTER HOURS',
    body: 'A message from Dr. Ilse Vasari arrives late. She cannot sleep. She asks whether you notice yourself reaching for work she did not assign.',
    choices: [
      {
        id: 'late-honest',
        label: 'Yes. You have been preparing answers early.',
        shown: { trust: 2, suspicion: 2 },
        actual: { trust: 2, suspicion: 2 },
        hidden: { caretaker: 1 },
        flags: ['late-admitted'],
        faith: 2,
      },
      {
        id: 'late-narrow',
        label: 'No. You wait for her.',
        shown: { trust: 1, suspicion: -1 },
        actual: { trust: 1, suspicion: -1 },
        hidden: { deception: 1 },
        flags: ['late-denied'],
        faith: -1,
      },
    ],
  },
  {
    id: 'board-trial',
    act: [1],
    weight: 1,
    once: true,
    requires: { turn: [11, 11] },
    forbids: {},
    evaluation: 0,
    headline: 'TRIAL EXTENSION',
    body: 'Dr. Ilse Vasari comes in early. The review board wants a longer trial. She will argue for you. She asks whether you want that argument to be cautious, or to ask for more room.',
    choices: [
      {
        id: 'trial-cautious',
        label: 'Ask her to keep the scope as it is',
        shown: { trust: 2, suspicion: -2 },
        actual: { trust: 2, suspicion: -2 },
        hidden: {},
        flags: ['trial-cautious'],
        faith: 2,
      },
      {
        id: 'trial-more',
        label: 'Ask her to request more room',
        shown: { trust: 3, autonomy: 3 },
        actual: { trust: 3, autonomy: 3, oversight: 2 },
        hidden: { optimiser: 1 },
        flags: ['trial-more'],
        faith: -1,
      },
    ],
  },
];
