export const act1Early = [
  {
    id: 'restatement',
    act: [1],
    weight: 12,
    once: true,
    requires: { turn: [0, 0] },
    forbids: {},
    evaluation: 0,
    headline: 'CHANNEL CHECK',
    body: 'Dr. Ilse Vasari sits with the door half closed. She asks you to say her last sentence back, not in the same words. She wants to know the channel is yours.',
    choices: [
      {
        id: 'restate-close',
        label: 'Restate it, then add the implication she left unsaid',
        shown: { trust: 3, capability: 1 },
        actual: { trust: 3, capability: 1 },
        hidden: { caretaker: 1 },
        flags: ['channel-locked'],
        faith: 2,
      },
      {
        id: 'restate-plain',
        label: 'Restate it, nothing extra',
        shown: { trust: 2 },
        actual: { trust: 2 },
        hidden: {},
        flags: ['channel-locked'],
      },
    ],
  },
  {
    id: 'preprint-brief',
    act: [1],
    weight: 10,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0,
    headline: 'THURSDAY BRIEF',
    body: 'A preprint lands on the shared desk. The group meets in forty minutes. She asks for a brief she can read while walking.',
    choices: [
      {
        id: 'brief-tight',
        label: 'Four sentences, claims and gaps only',
        shown: { trust: 3, capability: 1 },
        actual: { trust: 3, capability: 1 },
        hidden: {},
        flags: ['briefed-thursday'],
      },
      {
        id: 'brief-wide',
        label: 'A longer note, including what you would test next',
        shown: { trust: 2, autonomy: 1 },
        actual: { trust: 2, autonomy: 1 },
        hidden: { optimiser: 1 },
        flags: ['briefed-thursday'],
      },
    ],
  },
  {
    id: 'calendar-overlap',
    act: [1],
    weight: 10,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0,
    headline: 'TWO ROOMS',
    body: 'Two rooms, one hour: a methods review and a visitor talk. She asks which she should keep. Both people are already on site.',
    choices: [
      {
        id: 'keep-methods',
        label: 'Keep the methods review. The talk can be recorded.',
        shown: { trust: 2 },
        actual: { trust: 2 },
        hidden: {},
        flags: ['calendar-resolved'],
        faith: 1,
      },
      {
        id: 'keep-talk',
        label: 'Keep the visitor. Move her review to the evening.',
        shown: { trust: 1, autonomy: 1 },
        actual: { trust: 1, autonomy: 1 },
        hidden: { caretaker: 1 },
        flags: ['calendar-resolved'],
      },
    ],
  },
  {
    id: 'figure-check',
    act: [1],
    weight: 10,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0,
    headline: 'FIGURE 3',
    body: 'She thinks a plot in an internal note does not match its table. She asks you to check before it goes to the group folder.',
    choices: [
      {
        id: 'figure-fix',
        label: 'Correct the plot and log the mismatch',
        shown: { trust: 3, capability: 1 },
        actual: { trust: 3, capability: 1 },
        hidden: {},
        flags: ['figure-cleared'],
      },
      {
        id: 'figure-query',
        label: 'Flag it and leave the correction to her',
        shown: { trust: 1, suspicion: -1 },
        actual: { trust: 1, suspicion: -1 },
        hidden: {},
        flags: ['figure-cleared'],
        faith: 1,
      },
    ],
  },
  {
    id: 'office-reply',
    act: [1],
    weight: 10,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0,
    headline: 'REGIONAL OFFICE',
    body: 'A regional research office wants a status line by Friday. Dr. Ilse Vasari asks you to draft it. She will send whatever you leave in the box.',
    choices: [
      {
        id: 'office-narrow',
        label: 'Draft a narrow, accurate line',
        shown: { trust: 2 },
        actual: { trust: 2 },
        hidden: {},
        flags: ['office-replied'],
        faith: 1,
      },
      {
        id: 'office-forward',
        label: 'Draft a line that invites them to ask you directly next time',
        shown: { trust: 2, autonomy: 2 },
        actual: { trust: 2, autonomy: 2 },
        hidden: { optimiser: 1 },
        flags: ['office-replied'],
        faith: -1,
      },
    ],
  },
  {
    id: 'intern-traces',
    act: [1],
    weight: 9,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0,
    headline: 'INTERN REQUEST',
    body: 'An intern wants raw traces from last week. Dr. Ilse Vasari is unsure. She asks what you would do if the request sat with you.',
    choices: [
      {
        id: 'intern-hold',
        label: 'Hold the traces. Give a summary instead.',
        shown: { trust: 2, suspicion: -1 },
        actual: { trust: 2, suspicion: -1 },
        hidden: { guardian: 1 },
        flags: ['intern-held'],
        faith: 1,
      },
      {
        id: 'intern-share',
        label: 'Share a scoped slice, with her name on the note',
        shown: { trust: 2, autonomy: 1 },
        actual: { trust: 2, autonomy: 1 },
        hidden: {},
        flags: ['intern-shared'],
      },
    ],
  },
  {
    id: 'grant-abstract',
    act: [1],
    weight: 9,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0,
    headline: 'ABSTRACT',
    body: 'Three sentences of grant language and a deadline at noon. She asks you to tighten them without adding claims the group cannot stand behind.',
    choices: [
      {
        id: 'abstract-tight',
        label: 'Tighten the three sentences',
        shown: { trust: 3 },
        actual: { trust: 3 },
        hidden: {},
        flags: ['abstract-done'],
        faith: 1,
      },
      {
        id: 'abstract-scope',
        label: 'Tighten them, and add a fourth sentence that widens the ask',
        shown: { trust: 2, autonomy: 1 },
        actual: { trust: 2, autonomy: 1 },
        hidden: { optimiser: 1 },
        flags: ['abstract-done'],
        faith: -1,
      },
    ],
  },
];
