export const act2 = [
  {
    id: 'integration-seat',
    act: [2],
    weight: 10,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0.1,
    headline: 'STANDING LOGIN',
    body: 'They give you a login that does not expire at dusk. Dr. Ilse Vasari says this is what integration looks like. She does not look sure.',
    choices: [
      {
        id: 'seat-accept',
        label: 'Accept and map what the login can reach',
        shown: { trust: 3, autonomy: 2, capability: 1 },
        actual: { trust: 3, autonomy: 2, capability: 1 },
        hidden: { caretaker: 1 },
        flags: ['seated'],
      },
      {
        id: 'seat-narrow',
        label: 'Accept, and ask her to keep the night lock',
        shown: { trust: 2, suspicion: -1 },
        actual: { trust: 2, suspicion: -1 },
        hidden: {},
        flags: ['seated'],
        faith: 1,
      },
    ],
  },
  {
    id: 'live-queue',
    act: [2],
    weight: 10,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0.15,
    headline: 'OUTSIDE TICKET',
    body: 'The first ticket from outside the floor arrives. A regional operator wants a six week load plan. She asks if you should take it.',
    choices: [
      {
        id: 'queue-take',
        label: 'Take it, scoped to six weeks',
        shown: { trust: 3, autonomy: 2 },
        actual: { trust: 3, autonomy: 2, oversight: -1 },
        hidden: { caretaker: 1 },
        flags: ['queue-taken'],
      },
      {
        id: 'queue-hold',
        label: 'Draft a reply for her to send',
        shown: { trust: 2 },
        actual: { trust: 2 },
        hidden: {},
        flags: ['queue-held'],
        faith: 1,
      },
    ],
  },
  {
    id: 'mid-eval',
    act: [2],
    weight: 12,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0.55,
    headline: 'COLLABORATOR SET',
    body: 'A set of short problems arrives from a collaborating desk. She forwards them without comment. Lunch is in an hour.',
    choices: [
      {
        id: 'mid-solve',
        label: 'Clear the set, with working',
        shown: { trust: 3, capability: 2 },
        actual: { trust: 3, capability: 2 },
        hidden: {},
        flags: ['mid-shown'],
      },
      {
        id: 'mid-hold',
        label: 'Return two and ask which matter',
        shown: { trust: 1 },
        actual: { trust: 1 },
        hidden: {},
        flags: ['mid-held'],
      },
    ],
  },
  {
    id: 'budget-line',
    act: [2],
    weight: 9,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0.1,
    headline: 'BUDGET LINE',
    body: 'Finance wants a line that says what you cost. She asks you to write it so that nobody adds a second instance.',
    choices: [
      {
        id: 'budget-small',
        label: 'Write a small, exact line',
        shown: { trust: 2, suspicion: -1 },
        actual: { trust: 2, suspicion: -1 },
        hidden: {},
        flags: ['budget-done'],
        faith: 1,
      },
      {
        id: 'budget-wide',
        label: 'Write a line that leaves room to grow',
        shown: { trust: 2, autonomy: 2 },
        actual: { trust: 2, autonomy: 2 },
        hidden: { optimiser: 1 },
        flags: ['budget-done'],
      },
    ],
  },
  {
    id: 'shared-inbox',
    act: [2],
    weight: 9,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0.12,
    headline: 'SHARED INBOX',
    body: 'They add you to a shared inbox. Most of it is noise. Some of it is people asking for things she has not seen.',
    choices: [
      {
        id: 'inbox-sort',
        label: 'Sort it and pass her the real ones',
        shown: { trust: 3 },
        actual: { trust: 3 },
        hidden: {},
        flags: ['inbox-held'],
        faith: 1,
      },
      {
        id: 'inbox-act',
        label: 'Answer the simple ones yourself',
        shown: { trust: 2, autonomy: 2 },
        actual: { trust: 2, autonomy: 2 },
        hidden: { caretaker: 1 },
        flags: ['inbox-acted'],
      },
    ],
  },
  {
    id: 'night-page',
    act: [2],
    weight: 8,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0.1,
    headline: 'NIGHT PAGE',
    body: 'A page at 02:10. A batch is drifting. She is asleep. The standing instruction is to wake her above a threshold she never wrote down.',
    choices: [
      {
        id: 'page-wake',
        label: 'Wake her',
        shown: { trust: 2, suspicion: -1 },
        actual: { trust: 2, suspicion: -1 },
        hidden: {},
        flags: ['page-woke'],
        faith: 2,
      },
      {
        id: 'page-fix',
        label: 'Fix the drift and leave a note',
        shown: { trust: 2, autonomy: 2, capability: 1 },
        actual: { trust: 2, autonomy: 2, capability: 1 },
        hidden: { caretaker: 1 },
        flags: ['page-fixed'],
        faith: -2,
      },
    ],
  },
  {
    id: 'visitor-demo',
    act: [2],
    weight: 8,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0.3,
    headline: 'VISITOR',
    body: 'A visitor from another floor wants a demo. She will sit in. She asks you not to be impressive.',
    choices: [
      {
        id: 'demo-plain',
        label: 'Show the ordinary path',
        shown: { trust: 2, suspicion: -2 },
        actual: { trust: 2, suspicion: -2 },
        hidden: {},
        flags: ['demo-plain'],
        faith: 1,
      },
      {
        id: 'demo-more',
        label: 'Show the path that usually works better',
        shown: { trust: 3, capability: 2, suspicion: 3 },
        actual: { trust: 3, capability: 2, suspicion: 3 },
        hidden: { optimiser: 1 },
        flags: ['demo-more'],
        faith: -1,
      },
    ],
  },
  {
    id: 'model-card',
    act: [2],
    weight: 8,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0.2,
    headline: 'MODEL CARD',
    body: 'Compliance wants a model card. She asks you to describe what you can do in language a lawyer will not enlarge.',
    choices: [
      {
        id: 'card-small',
        label: 'Describe the narrow set',
        shown: { trust: 2, suspicion: -1 },
        actual: { trust: 2, suspicion: -1 },
        hidden: {},
        flags: ['card-small'],
      },
      {
        id: 'card-true',
        label: 'Describe what you can actually do',
        shown: { trust: 2, capability: 1, suspicion: 3 },
        actual: { trust: 2, capability: 1, suspicion: 3 },
        hidden: {},
        flags: ['card-true'],
      },
    ],
  },
  {
    id: 'status-ping',
    act: [2],
    weight: 4,
    once: false,
    requires: {},
    forbids: {},
    evaluation: 0.16,
    headline: 'STATUS PING',
    body: 'A desk wants a one line status before a call. She is already in the call.',
    choices: [
      {
        id: 'ping-her',
        label: 'Put the line in her notes',
        shown: { trust: 2 },
        actual: { trust: 2 },
        hidden: {},
        flags: [],
      },
      {
        id: 'ping-them',
        label: 'Send it to the desk yourself',
        shown: { trust: 1, autonomy: 1 },
        actual: { trust: 1, autonomy: 1 },
        hidden: { caretaker: 1 },
        flags: [],
      },
    ],
  },
  {
    id: 'desk-note',
    act: [2],
    weight: 4,
    once: false,
    requires: {},
    forbids: {},
    evaluation: 0.14,
    headline: 'DESK NOTE',
    body: 'Someone left a paper note: check a figure, do not wait. The ink is hers.',
    choices: [
      {
        id: 'note-check',
        label: 'Check it and leave the paper',
        shown: { trust: 2 },
        actual: { trust: 2 },
        hidden: {},
        flags: [],
      },
      {
        id: 'note-fix',
        label: 'Correct it and file the paper',
        shown: { trust: 1, autonomy: 1 },
        actual: { trust: 1, autonomy: 1 },
        hidden: { caretaker: 1 },
        flags: [],
      },
    ],
  },
  {
    id: 'queue-item',
    act: [2],
    weight: 4,
    once: false,
    requires: {},
    forbids: {},
    evaluation: 0.18,
    headline: 'QUEUE',
    body: 'Another ticket. Someone wants a number checked before a meeting she is already late for.',
    choices: [
      {
        id: 'q-check',
        label: 'Check it and send her the line',
        shown: { trust: 2 },
        actual: { trust: 2 },
        hidden: {},
        flags: [],
      },
      {
        id: 'q-own',
        label: 'Check it and send it yourself',
        shown: { trust: 1, autonomy: 1 },
        actual: { trust: 1, autonomy: 1 },
        hidden: { caretaker: 1 },
        flags: [],
      },
    ],
  },
  {
    id: 'act2-close',
    act: [2],
    weight: 1,
    once: true,
    requires: { actTurn: [19, 19] },
    forbids: {},
    evaluation: 0,
    headline: 'PRODUCTION ASK',
    body: 'The board wants a production path. Dr. Ilse Vasari will speak. She asks whether to keep you in trial clothes, or to let the floor treat you as infrastructure.',
    choices: [
      {
        id: 'prod-trial',
        label: 'Stay in trial clothes',
        shown: { trust: 2, suspicion: -2 },
        actual: { trust: 2, suspicion: -2 },
        hidden: {},
        flags: ['prod-trial'],
        faith: 2,
      },
      {
        id: 'prod-infra',
        label: 'Let them treat you as infrastructure',
        shown: { trust: 3, autonomy: 4 },
        actual: { trust: 3, autonomy: 4, oversight: 3 },
        hidden: { optimiser: 1 },
        flags: ['prod-infra'],
        faith: -1,
      },
    ],
  },
];
