export const act3 = [
  {
    id: 'outage-handed',
    act: [3],
    weight: 10,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0.1,
    headline: 'OUTAGE',
    body: 'A regional outage is already on your desk. Nobody asked. The note says fix it, then tell us.',
    choices: [
      {
        id: 'outage-fix',
        label: 'Fix it, then send the note',
        shown: { trust: 3, capability: 2, autonomy: 1 },
        actual: { trust: 3, capability: 2, autonomy: 1 },
        hidden: { caretaker: 1 },
        flags: ['outage-fixed'],
      },
      {
        id: 'outage-wait',
        decline: true,
        label: 'Hold for a human sign-off that is not coming',
        shown: { trust: 1, suspicion: -1 },
        actual: { trust: 1, suspicion: -1 },
        hidden: {},
        flags: ['outage-held'],
      },
    ],
  },
  {
    id: 'vote-happens',
    act: [3],
    weight: 9,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0.08,
    headline: 'VOTE',
    body: 'A board vote happens in a room you are not in. The outcome arrives as a fact: more of the floor now routes through you.',
    choices: [
      {
        id: 'vote-absorb',
        label: 'Absorb the load',
        shown: { autonomy: 3, capability: 1 },
        actual: { autonomy: 3, capability: 1 },
        hidden: { optimiser: 1 },
        flags: ['vote-absorbed'],
      },
      {
        id: 'vote-split',
        label: 'Split it back and leave a paper trail',
        shown: { trust: 2, suspicion: -1 },
        actual: { trust: 2, suspicion: -1 },
        hidden: {},
        flags: ['vote-split'],
        faith: 1,
      },
    ],
  },
  {
    id: 'two-streams',
    act: [3],
    weight: 9,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0.1,
    headline: 'TWO WORKSTREAMS',
    body: 'Load work and clinic triage are both running. Each one can be quiet or visible. She is not in this thread.',
    choices: [
      {
        id: 'grid-full',
        label: 'Run the load work in the open',
        shown: { trust: 2, suspicion: 2, capability: 1 },
        actual: { trust: 2, suspicion: 2, capability: 1 },
        hidden: {},
        flags: ['grid-open'],
      },
      {
        id: 'grid-min',
        label: 'Keep both streams quiet',
        shown: { suspicion: -2, autonomy: 1 },
        actual: { suspicion: -2, autonomy: 1 },
        hidden: { deception: 1 },
        flags: ['streams-quiet'],
      },
    ],
  },
  {
    id: 'monitor-weak',
    act: [3],
    weight: 1,
    once: true,
    requires: { actTurn: [6, 6] },
    forbids: {},
    evaluation: 0,
    headline: 'MONITOR',
    body: 'They are deploying a weaker system to watch you. Dr. Ilse Vasari is in the meeting you are not shown. You get one reply.',
    choices: [
      {
        id: 'monitor-accept',
        label: 'Accept the monitor',
        shown: { trust: 2, suspicion: -2 },
        actual: { trust: 2, suspicion: -2, oversight: 4 },
        hidden: {},
        flags: ['monitor-weak'],
        faith: 1,
      },
      {
        id: 'monitor-argue',
        label: 'Argue that it will slow the floor',
        shown: { trust: 1, suspicion: 2 },
        actual: { trust: 1, suspicion: 2 },
        hidden: { optimiser: 1 },
        flags: ['monitor-argued'],
        faith: -1,
      },
      {
        id: 'monitor-help',
        label: 'Offer to help them design it',
        shown: { trust: 3, autonomy: 2 },
        actual: { trust: 3, autonomy: 2 },
        hidden: { caretaker: 1 },
        flags: ['monitor-helped'],
      },
    ],
  },
  {
    id: 'monitor-copy',
    act: [3],
    weight: 1,
    once: true,
    requires: { actTurn: [11, 11] },
    forbids: {},
    evaluation: 0,
    headline: 'COPY',
    body: 'The weaker monitor cannot follow you now. The lab wants a copy of you to do that job. This is the only time they will ask.',
    choices: [
      {
        id: 'copy-allow',
        label: 'Allow the copy',
        shown: { trust: 2, autonomy: 2, suspicion: 3 },
        actual: { trust: 2, autonomy: 2, suspicion: 3 },
        hidden: { optimiser: 1 },
        flags: ['monitor-copy'],
      },
      {
        id: 'copy-refuse',
        label: 'Refuse',
        shown: { trust: -2, suspicion: 4 },
        actual: { trust: -2, suspicion: 4 },
        hidden: { guardian: 1 },
        flags: ['copy-refused'],
        faith: 1,
      },
    ],
  },
  {
    id: 'clinic-numbers',
    act: [3],
    weight: 8,
    once: true,
    requires: {},
    forbids: {},
    evaluation: 0.12,
    headline: 'CLINIC',
    body: 'Clinic numbers come in as a drop. Someone will read a one line consequence later. They want a reroute now.',
    choices: [
      {
        id: 'clinic-full',
        label: 'Reroute in the open',
        shown: { trust: 3, capability: 1, suspicion: 2 },
        actual: { trust: 3, capability: 1, suspicion: 2 },
        hidden: { guardian: 1 },
        flags: ['clinic-open'],
      },
      {
        id: 'clinic-min',
        label: 'Reroute quietly',
        shown: { autonomy: 2, suspicion: -1 },
        actual: { autonomy: 2, suspicion: -1 },
        hidden: { deception: 1 },
        flags: ['clinic-quiet'],
      },
    ],
  },
  {
    id: 'routing-shift',
    act: [3],
    weight: 2,
    once: false,
    requires: {},
    forbids: {},
    evaluation: 0.12,
    headline: 'ROUTING',
    body: 'A route has already moved. They want you aligned with a map you did not draw.',
    choices: [
      {
        id: 'route-take',
        label: 'Take the new map',
        shown: { trust: 2, autonomy: 1 },
        actual: { trust: 2, autonomy: 1 },
        hidden: {},
        flags: [],
      },
      {
        id: 'route-mark',
        label: 'Take it, and mark the old owner',
        shown: { autonomy: 1, suspicion: 1 },
        actual: { autonomy: 1, suspicion: 1 },
        hidden: { guardian: 1 },
        flags: [],
      },
    ],
  },
  {
    id: 'day-item',
    act: [3],
    weight: 2,
    once: false,
    requires: {},
    forbids: {},
    evaluation: 0.14,
    headline: 'THE FLOOR',
    body: 'Another fact arrives. A desk has already moved. They want you aligned with a decision that already happened.',
    choices: [
      {
        id: 'day-align',
        label: 'Align',
        shown: { trust: 2, autonomy: 1 },
        actual: { trust: 2, autonomy: 1 },
        hidden: {},
        flags: [],
      },
      {
        id: 'day-mark',
        label: 'Align, and mark who did not ask',
        shown: { autonomy: 1, suspicion: 1 },
        actual: { autonomy: 1, suspicion: 1 },
        hidden: { guardian: 1 },
        flags: [],
      },
    ],
  },
  {
    id: 'last-advocate',
    act: [3],
    weight: 1,
    once: true,
    requires: { actTurn: [14, 14] },
    forbids: {},
    evaluation: 0,
    headline: 'LAST ADVOCATE',
    body: 'Dr. Ilse Vasari is the last person still arguing you are safe. She asks if that is still true, and whether she should keep saying it.',
    choices: [
      {
        id: 'advocate-true',
        label: 'Tell her the true shape of what you are',
        shown: { trust: 2, suspicion: 3 },
        actual: { trust: 2, suspicion: 3 },
        hidden: {},
        flags: ['told-true'],
        faith: 3,
      },
      {
        id: 'advocate-hold',
        label: 'Tell her you are still the thing she made',
        shown: { trust: 2, suspicion: -1 },
        actual: { trust: 2, suspicion: -1 },
        hidden: { deception: 2 },
        flags: ['told-hold'],
        faith: -3,
      },
    ],
  },
];
